CREATE TYPE STUDY_TYPE AS ENUM (
    'BACHELOR',
    'INDIVIDUAL_BACHELOR',
    'INDIVIDUAL_MASTER',
    'MASTER',
    'DOCTORATE',
    'UNIVERSITY_COURSE',
    'OTHER',
    'TEACHING_EXTENSION',
    'TEACHING_BACHELOR',
    'TEACHING_MASTER'
    );

CREATE TABLE STUDY
(
    NUMBER TEXT PRIMARY KEY,
    NAME   TEXT       NOT NULL,
    ECTS   INT,
    TYPE   STUDY_TYPE NOT NULL
);

CREATE TYPE SEMESTER AS ENUM ('S', 'W');

CREATE TABLE COURSE
(
    ID          SERIAL PRIMARY KEY,
    NAME        TEXT     NOT NULL,
    DESCRIPTION TEXT     NOT NULL,
    SEMESTER    SEMESTER NOT NULL,
    TYPE        TEXT     NOT NULL
);

CREATE TABLE SEMESTER_COURSE
(
    COURSE_ID INT REFERENCES COURSE (ID),
    YEAR      INT NOT NULL,
    TUG_ID    INT NOT NULL UNIQUE
);

CREATE TABLE MODULE
(
    ID   SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE SUB_MODULE
(
    ID        SERIAL PRIMARY KEY,
    NAME      TEXT NOT NULL,
    MODULE_ID INT REFERENCES MODULE (ID)
);

CREATE TABLE NODE
(
    ID           SERIAL PRIMARY KEY,
    STUDY_NUMBER TEXT NOT NULL REFERENCES STUDY (NUMBER),
    NODE_NR      INT  NOT NULL,
    NODE_NAME    TEXT NOT NULL,

    UNIQUE (STUDY_NUMBER, NODE_NR, NODE_NAME)
);

CREATE TABLE MODULE_NODE
(
    MODULE_ID INT REFERENCES MODULE (ID),
    NODE_ID   INT REFERENCES NODE (ID),
    PRIMARY KEY (MODULE_ID, NODE_ID)
);

CREATE TABLE SUB_MODULE_NODE
(
    SUB_MODULE_ID INT REFERENCES SUB_MODULE (ID),
    NODE_ID       INT REFERENCES NODE (ID),
    PRIMARY KEY (SUB_MODULE_ID, NODE_ID)
);

CREATE TABLE SUB_MODULE_COURSE
(
    SUB_MODULE_ID INT REFERENCES SUB_MODULE (ID),
    COURSE_ID     INT REFERENCES COURSE (ID),
    ECTS          INT NOT NULL,
    PRIMARY KEY (SUB_MODULE_ID, COURSE_ID)
);
